version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres